# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'morphingUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 331, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.SourceImg = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.SourceImg.setContentsMargins(0, 0, 0, 0)
        self.SourceImg.setSpacing(10)
        self.SourceImg.setObjectName("SourceImg")
        self.sourceImg = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.sourceImg.setObjectName("sourceImg")
        self.SourceImg.addWidget(self.sourceImg)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 240, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.source_load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.source_load.setObjectName("source_load")
        self.horizontalLayout.addWidget(self.source_load)
        self.source_draw = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.source_draw.setObjectName("source_draw")
        self.horizontalLayout.addWidget(self.source_draw)
        self.source_finish = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.source_finish.setObjectName("source_finish")
        self.horizontalLayout.addWidget(self.source_finish)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 510, 331, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.target_load = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.target_load.setObjectName("target_load")
        self.horizontalLayout_2.addWidget(self.target_load)
        self.target_draw = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.target_draw.setObjectName("target_draw")
        self.horizontalLayout_2.addWidget(self.target_draw)
        self.target_finish = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.target_finish.setObjectName("target_finish")
        self.horizontalLayout_2.addWidget(self.target_finish)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 290, 331, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.SourceImg_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.SourceImg_2.setContentsMargins(0, 0, 0, 0)
        self.SourceImg_2.setSpacing(10)
        self.SourceImg_2.setObjectName("SourceImg_2")
        self.targetImg = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.targetImg.setObjectName("targetImg")
        self.SourceImg_2.addWidget(self.targetImg)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(380, 20, 441, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Result = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Result.setContentsMargins(0, 0, 0, 0)
        self.Result.setObjectName("Result")
        self.result = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        self.result.setObjectName("result")
        self.Result.addWidget(self.result)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(380, 350, 441, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Parameters = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Parameters.setContentsMargins(0, 0, 0, 0)
        self.Parameters.setObjectName("Parameters")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time.setObjectName("time")
        self.horizontalLayout_6.addWidget(self.time)
        self.timSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.timSpinBox.setObjectName("timSpinBox")
        self.horizontalLayout_6.addWidget(self.timSpinBox)
        self.second = QtWidgets.QLabel(self.gridLayoutWidget)
        self.second.setObjectName("second")
        self.horizontalLayout_6.addWidget(self.second)
        self.Parameters.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.a = QtWidgets.QLabel(self.gridLayoutWidget)
        self.a.setObjectName("a")
        self.horizontalLayout_3.addWidget(self.a)
        self.aSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.aSlider.setSingleStep(5)
        self.aSlider.setPageStep(20)
        self.aSlider.setOrientation(QtCore.Qt.Horizontal)
        self.aSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.aSlider.setObjectName("aSlider")
        self.horizontalLayout_3.addWidget(self.aSlider)
        self.Parameters.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.speed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed.setObjectName("speed")
        self.horizontalLayout_7.addWidget(self.speed)
        self.speedSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.horizontalLayout_7.addWidget(self.speedSpinBox)
        self.frame_per_second = QtWidgets.QLabel(self.gridLayoutWidget)
        self.frame_per_second.setObjectName("frame_per_second")
        self.horizontalLayout_7.addWidget(self.frame_per_second)
        self.Parameters.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b = QtWidgets.QLabel(self.gridLayoutWidget)
        self.b.setObjectName("b")
        self.horizontalLayout_4.addWidget(self.b)
        self.bSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.bSlider.setMinimum(5)
        self.bSlider.setMaximum(20)
        self.bSlider.setSingleStep(1)
        self.bSlider.setPageStep(5)
        self.bSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bSlider.setObjectName("bSlider")
        self.horizontalLayout_4.addWidget(self.bSlider)
        self.Parameters.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.p = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p.setObjectName("p")
        self.horizontalLayout_5.addWidget(self.p)
        self.pSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.pSlider.setMaximum(100)
        self.pSlider.setSingleStep(10)
        self.pSlider.setPageStep(20)
        self.pSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.pSlider.setObjectName("pSlider")
        self.horizontalLayout_5.addWidget(self.pSlider)
        self.Parameters.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout_8.addWidget(self.save)
        self.play = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.play.setObjectName("play")
        self.horizontalLayout_8.addWidget(self.play)
        self.Parameters.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Morphing Program"))
        self.sourceImg.setTitle(_translate("MainWindow", "Source Image"))
        self.source_load.setText(_translate("MainWindow", "Load"))
        self.source_draw.setText(_translate("MainWindow", "Draw"))
        self.source_finish.setText(_translate("MainWindow", "Finish"))
        self.target_load.setText(_translate("MainWindow", "Load"))
        self.target_draw.setText(_translate("MainWindow", "Draw"))
        self.target_finish.setText(_translate("MainWindow", "Finish"))
        self.targetImg.setTitle(_translate("MainWindow", "Target Image"))
        self.result.setTitle(_translate("MainWindow", "Result Image"))
        self.time.setText(_translate("MainWindow", "time:"))
        self.second.setText(_translate("MainWindow", "s"))
        self.a.setText(_translate("MainWindow", "a:"))
        self.speed.setText(_translate("MainWindow", "speed:"))
        self.frame_per_second.setText(_translate("MainWindow", "f/s"))
        self.b.setText(_translate("MainWindow", "b:"))
        self.p.setText(_translate("MainWindow", "p:"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.play.setText(_translate("MainWindow", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

